export enum ActionTypes {
    SEARCH_IMAGES = "SEARCH_IMAGES",
    SEARCH_IMAGES_SUCCESS = "SEARCH_IMAGES_SUCCESS",
    SEARCH_IMAGES_ERROR = "SEARCH_IMAGES_ERROR",
    FETCH_RANDOM_IMAGES = "FETCH_RANDOM_IMAGES",
    FETCH_RANDOM_IMAGES_SUCCESS = "FETCH_RANDOM_IMAGES_SUCCESS",
    FETCH_RANDOM_IMAGES_ERROR = "FETCH_RANDOM_IMAGES_ERROR",
    SEARCH_HISTORY_ADD = "SEARCH_HISTORY_ADD",
    SEARCH_HISTORY_REMOVE = "SEARCH_HISTORY_REMOVE",
}
